version: '3'
services:
  opencart:
    build: tools
    user: 1000:1000
    ports:
      - "80:80"
    volumes:
      - ./upload:/var/www/html
    depends_on:
      - mysql
    command: >
      bash -c "
        cd /var/www/html &&
        if [ ! -f install.lock ]; then
          echo '‚è≥ Waiting for MySQL...';
          sleep 15;

          cp config-dist.php config.php &&
          cp admin/config-dist.php admin/config.php &&

          php install/cli_install.php install \
            --username admin \
            --password admin \
            --email email@example.com \
            --http_server http://localhost/ \
            --db_driver mysqli \
            --db_hostname mysql \
            --db_username root \
            --db_password opencart \
            --db_database opencart \
            --db_port 3306 \
            --db_prefix oc_;

          touch install.lock;
        fi;

        apache2-foreground
      "

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: opencart
      MYSQL_DATABASE: opencart
    command: --default-authentication-plugin=mysql_native_password

  adminer:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    depends_on:
      - mysql
    ports:
      - "8081:8080"

  redis:
    image: redis:latest

  memcached:
    image: memcached:latest

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: opencart
      POSTGRES_DB: opencart
